# Numpy assignment
- Different tasks will be detailed by comments or text.
- For further reference and resources, it's advised to check out the NumPy documentation.

In [2]:
# Import NumPy as its abbreviation 'np'
import numpy as np


In [3]:
# Create a 1-dimensional NumPy array using np.array()
b1 = np.array( [1,2,3,4,5])

# Create a 2-dimensional NumPy array using np.array()
a1 = np.array([[1,2,3],[3,4,5]])
  

In [4]:
# Attributes of 1-dimensional array (shape, number of dimensions, data type, size and type)
print("Shape: ",b1.shape)
print("No of Dimensions: ",b1.ndim)
print("Size: ",b1.size)
print("Type: ",b1.dtype)

Shape:  (5,)
No of Dimensions:  1
Size:  5
Type:  int32


In [5]:
# Attributes of 2-dimensional array
print("Shape: ",a1.shape)
print("No of Dimensions: ",a1.ndim)
print("Size: ",a1.size)
print("Type: ",a1.dtype)


Shape:  (2, 3)
No of Dimensions:  2
Size:  6
Type:  int32


In [6]:
# Create an array of shape (5, 5) with only ones
b2 = np.ones((5,5), np.int64)
b2


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

In [7]:
# Create an array of shape (3, 3, 5) with only zeros
b3 = np.zeros((3,3,5),np.int64)
b3


array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]], dtype=int64)

In [8]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
b4 = np.random.randint(0,10,(7,2), np.int64)
b4

array([[3, 2],
       [9, 5],
       [5, 4],
       [1, 1],
       [1, 8],
       [6, 4],
       [1, 0]], dtype=int64)

In [9]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
b5 = np.random.rand(3,5)
b5

array([[0.98642292, 0.15194227, 0.04738304, 0.53886208, 0.18050225],
       [0.0837242 , 0.709889  , 0.8129453 , 0.84282712, 0.011566  ],
       [0.20992691, 0.47464397, 0.47382812, 0.80767371, 0.67127581]])

In [10]:
# Create an array of normally distributed random numbers
b6 = np.random.randn(5)
b6


array([ 0.17475444,  0.92282959, -0.6713916 ,  0.38474787, -0.43640062])

In [11]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
b7 = np.random.rand(4,6)
b7

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
        0.15599452],
       [0.05808361, 0.86617615, 0.60111501, 0.70807258, 0.02058449,
        0.96990985],
       [0.83244264, 0.21233911, 0.18182497, 0.18340451, 0.30424224,
        0.52475643],
       [0.43194502, 0.29122914, 0.61185289, 0.13949386, 0.29214465,
        0.36636184]])

In [12]:
# Copy the code from the cell above and run it again
np.random.seed(42)
b7 = np.random.rand(4,6)
b7


array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
        0.15599452],
       [0.05808361, 0.86617615, 0.60111501, 0.70807258, 0.02058449,
        0.96990985],
       [0.83244264, 0.21233911, 0.18182497, 0.18340451, 0.30424224,
        0.52475643],
       [0.43194502, 0.29122914, 0.61185289, 0.13949386, 0.29214465,
        0.36636184]])

In [13]:
# Find the 0'th index of the latest array you created
print(b7[0][0])

0.3745401188473625


In [15]:
# Get the first 2 rows of latest array you created
r1=b7[0]
r2=b7[1]
print(r1,"\n",r2)

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452] 
 [0.05808361 0.86617615 0.60111501 0.70807258 0.02058449 0.96990985]


In [16]:
# Get the first 2 values of the first 2 rows of the latest array
r1v1 = r1[0]
r2v1 = r2[0]
print(r1v1,"\n",r2v1)


0.3745401188473625 
 0.05808361216819946


In [22]:
# Create a random array of numbers between 0 & 10 and an array of ones both of size (3, 5), save them both to variables
b8 = np.random.randint(0,10,(3,5), np.int64)
b9 = np.ones( (3,5), np.int(64))

TypeError: data type not understood

In [21]:
# Add the two arrays together

b10 = b8+b9

NameError: name 'b9' is not defined

In [23]:
# Create another array of ones of shape (5, 3)
a4 = np.ones( (5,3), np.int64)


In [24]:
# Try add the array of ones and the other most recent array together # You can anticipate an error
b10+a4

NameError: name 'b10' is not defined

In [9]:
# Do the same operation you just did but this time with a transpose on one array


In [27]:
# Take the latest array to the power of 2 using the python way
b7**2

array([[1.40280301e-01, 9.03857692e-01, 5.35815131e-01, 3.58391981e-01,
        2.43418162e-02, 2.43342904e-02],
       [3.37370600e-03, 7.50261116e-01, 3.61339257e-01, 5.01366775e-01,
        4.23721405e-04, 9.40725121e-01],
       [6.92960750e-01, 4.50878979e-02, 3.30603187e-02, 3.36372142e-02,
        9.25633424e-02, 2.75369313e-01],
       [1.86576499e-01, 8.48144121e-02, 3.74363965e-01, 1.94585372e-02,
        8.53484957e-02, 1.34221000e-01]])

In [28]:
# Do the same thing with numpy way
np.power(b7,2)

array([[1.40280301e-01, 9.03857692e-01, 5.35815131e-01, 3.58391981e-01,
        2.43418162e-02, 2.43342904e-02],
       [3.37370600e-03, 7.50261116e-01, 3.61339257e-01, 5.01366775e-01,
        4.23721405e-04, 9.40725121e-01],
       [6.92960750e-01, 4.50878979e-02, 3.30603187e-02, 3.36372142e-02,
        9.25633424e-02, 2.75369313e-01],
       [1.86576499e-01, 8.48144121e-02, 3.74363965e-01, 1.94585372e-02,
        8.53484957e-02, 1.34221000e-01]])

In [29]:
# Find the mean, min, max, standard deviation, variance of the latest array using np.mean
print(np.mean(b7),"\n",np.max(b7),"\n",np.min(b7),"\n",np.std(b7),"\n",np.var(b7))

0.44016245896496015 
 0.9699098521619943 
 0.020584494295802447 
 0.2852002868196039 
 0.08133920360198434


In [31]:
# Create two arrays of random integers between 0 to 10 one of size (3, 3) the other of size (3, 2)
c1=np.random.randint(0,10,(3,3),np.int64)
c2=np.random.randint(0,10,(3,2),np.int64)


In [32]:
# Perform a dot product on the two newest arrays you created
cd = np.dot(c1,c2)
print(cd)


[[52 87]
 [40 79]
 [14 20]]


In [33]:
# Create two arrays of random integers between 0 to 10 both of size (4, 3)
q1 = np.random.randint(0,10,(4,3),np.int64)
q2 = np.random.randint(0,10,(4,3),np.int64)

In [35]:
# Perform a hadamard product on the two newest arrays you created
qmard = np.multiply(q1,q2)
qmard

array([[36, 18, 48],
       [18, 45,  2],
       [54,  0, 12],
       [15, 12, 54]], dtype=int64)

In [36]:
# Perform a dot product on the two newest arrays you created # Error anticipated
qdaot = np.dot(q1,q2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [38]:
# Take the latest two arrays, perform a transpose on one of them and then perform a dot product on them both
qdot = np.dot( q1,np.transpose(q2))
qdot

array([[102,  50, 134, 120],
       [ 93,  65, 161,  90],
       [ 54,  15,  66,  57],
       [ 66,  32,  83,  81]], dtype=int64)

In [39]:
# Create two arrays of random integers between 0 & 10 of the same shape and save them to variables
q3 = np.random.randint(0,10,5)
q4 = np.random.randint(0,10,5)

In [40]:
# Compare the two arrays with '>', '<=' and '==' 
print(q3>q4)
print(q3<=q4)
print(q3==q4)

[False False  True False False]
[ True  True False  True  True]
[False  True False False False]


In [41]:
# Sort one of the arrays you just created in ascending order
np.sort(q3)

array([0, 0, 6, 6, 8])

In [42]:
# Sort the indexes of one of the arrays you just created
print(np.argsort(q3))

[3 4 0 2 1]


In [43]:
# Find the index with the maximum value in one of the arrays you've created
print(np.argmax(q3))

1


In [45]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [48]:
# Find the indexes with the maximum values down the verticial axis of one of the arrays you created
np.argmax(q1,axis = 1)

array([2, 0, 0, 2], dtype=int64)

In [49]:
# Find the indexes with the minimum values across the horizontal axis of one of the arrays you created
np.argmin(q1,axis=0)

array([3, 2, 1], dtype=int64)